# ICONVIET MEGALOOP Contract API

## Sample call

Testnet endpoint: https://bicon.net.solidwallet.io/api/v3

Mainnet endpoint: https://ctz.solidwallet.io/api/v3

WARNING: Don't forget to remove all comments before sending

POST Request
[source]
{
    "jsonrpc": "2.0",
    "method": "icx_call",
    "id": 1234,
    "params": {
        "from": "hx077a0fb5efe377e2481ce97c8432969ec156ef1e", // TX sender address
        "to": "cxa6ba8f0730ad952b5898ac3e5e90a17e20574eff",   // SCORE address
        "dataType": "call",
        "data": {
            "method": "about", // SCORE external function
            "params": {}
        }
    }
}

## External functions and sample return

<<get_jackpot_size>>

<<get_max_subsidy>>

<<get_pot_limit>>

<<get_commission>>

<<get_top_deposit>>

<<ls_players>>

<<get_player>>

<<get_last_winner>>

<<get_last_settlement_bh>>

<<get_last_settlement_tx>>

[[get_jackpot_size]]
### get_jackpot_size

Get current jackpot size of ongoing round

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<int_digits_in_loops>", // For instance, "4320000...0000" is 4.32 ICX
    "id": 1234
}

[[get_max_subsidy]]
### get_max_subsidy

Get current subsidy amount set by ICONVIET

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<int_digits_in_loops>",
    "id": 1234
}

[[get_pot_limit]]
### get_pot_limit

Jackpot size limit

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<int_digits_in_loops>",
    "id": 1234
}

[[get_commission]]
### get_commission

Commission the contract will take for each winner drawing, in percentage of jackpot

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<int_digits>", // "5" is 5 %
    "id": 1234
}

[[get_top_deposit]]
### get_top_deposit

Get highest ICX deposit recorded in current round

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<int_digits_in_loops>",
    "id": 1234
}

[[ls_players]]
### ls_players

List of players in current round and their deposit

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": [
        "hx94bd58b8073779e742d9e4c167ef8dc73a4406aa:691400000000000000:610401",
        "hx7d2afae54e1c3fffb472108174bc92c8eec73d17:551400000000000000:610401",
        ...
        "<address>:<deposit_amount_in_loops>:<deposit_block_height>"
    ],
    "id": 1234
}

[[get_player]]
### get_player

Get record of one specific player in current round

*Params*
[source]
{
    "address": "hx...." // Player address
}

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<address>:<deposit_amount>:<deposit_block_height>",
    "id": 1234
}

[[get_last_winner]]
### get_last_winner

Record of the winner in previous round

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<block_height>:<address>:<deposit_size>:<total_prize_value>:<subsidy_value>",
    "id": 1234
}

[[get_last_player]]
### get_last_player

Record of the latest player in current round

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<address>:<deposit_amount>:<deposit_block_height>",
    "id": 1234
}

[[get_last_settlement_bh]]
### get_last_settlement_bh

The height of block contains previous winner drawing transaction

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "<int_digits_of_block_height>",
    "id": 1234
}

[[get_last_settlement_tx]]
### get_last_settlement_tx

Hash of previous winner drawing transaction

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": "0xa7936fbafc1653878ec04eb2dbf124915d7514aaf2bc447b81c37a319698bc98",
    "id": 1234
}

[[ls_winners]]
### ls_winners

List of all winners in previous rounds

*Return*
[source]
{
    "jsonrpc": "2.0",
    "result": [
        "649870:hx94bd58b8073779e742d9e4c167ef8dc73a4406aa:190000000000000000:400461800000000000000:400000000000000000000",
        "649890:hx94bd58b8073779e742d9e4c167ef8dc73a4406aa:601000000000000000:400665400000000000000:400000000000000000000",
        ...
        "<block_height>:<address>:<deposit_size>:<total_prize_value>:<subsidy_value>"
    ],
    "id": 1234
}
